import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Lang = "ar" | "en";

const translations = {
  ar: {
    // Navbar
    howItWorks: "كيف يعمل؟",
    features: "المميزات",
    admin: "المسؤول",
    dashboard: "لوحة التحكم",
    signOut: "تسجيل خروج",
    login: "تسجيل دخول",
    signupFree: "سجّل مجاناً",

    // Hero
    heroBadge: "احجز موقفك قبل ما توصل",
    heroTitle1: "ما تدور على",
    heroSpot: "موقف",
    heroTitle2: "خلّ أحد يحجزه لك",
    heroDesc: "تطبيق SuperParking يربطك بأشخاص قريبين من وجهتك يحجزون لك موقف سيارة بمركبتهم حتى توصل. وفّر وقتك وأعصابك!",
    statSpots: "موقف تم حجزه",
    statCrew: "حاجز نشط",
    statRating: "تقييم المستخدمين",

    // HowItWorks
    howLabel: "كيف يعمل؟",
    howTitle: "ثلاث خطوات بس",
    howDesc: "عملية سهلة وسريعة تخلّيك تحصل موقف بدون عناء",
    step1Title: "حدد وجهتك",
    step1Desc: "اكتب الموقع اللي تبي تروحه وحدد الوقت المتوقع لوصولك.",
    step2Title: "اختر الحاجز",
    step2Desc: "تصفح قائمة الحاجزين القريبين واختر الأنسب حسب التقييم والسعر.",
    step3Title: "أوصل وتلقى أحد أفراد طاقمنا حاجز لك موقف",
    step3Desc: "الحاجز يحفظ لك الموقف حتى توصل. استلم موقفك بكل راحة!",
    step1Tip: "اختر وجهتك ووقت الوصول",
    step2Tip: "اختر الحاجز الأنسب لك",
    step3Tip: "موقفك جاهز لما توصل",

    // Features
    whySuperParking: "ليش SuperParking؟",
    featuresTitle: "مميزات تخلّيك ترتاح",
    featSaveTime: "توفير الوقت",
    featSaveTimeDesc: "ما تحتاج تلف وتدور، موقفك جاهز قبل ما توصل.",
    featSafety: "أمان وثقة",
    featSafetyDesc: "جميع الحاجزين موثقين ومقيّمين من المستخدمين.",
    featPrice: "أسعار معقولة",
    featPriceDesc: "ادفع فقط مبلغ بسيط مقابل راحة بالك.",
    featRating: "نظام تقييم",
    featRatingDesc: "قيّم تجربتك واختر الحاجزين الأعلى تقييماً.",
    featChat: "تواصل مباشر",
    featChatDesc: "تواصل مع الحاجز مباشرة عبر الدردشة داخل التطبيق.",
    featTracking: "تتبع مباشر",
    featTrackingDesc: "تابع موقع الحاجز والموقف على الخريطة في الوقت الفعلي.",
    featSaveTimeTip: "موقفك جاهز قبل الوصول",
    featSafetyTip: "حاجزون موثقون ومقيّمون",
    featPriceTip: "سعر ثابت 29 ر.س",
    featRatingTip: "قيّم وشاهد التقييمات",
    featChatTip: "دردشة فورية داخل التطبيق",
    featTrackingTip: "تتبع الحاجز على الخريطة",

    // CTA
    ctaTitle: "جاهز تحجز موقفك؟",
    ctaDesc: "سجّل في SuperParking واحجز موقفك بكل سهولة",
    ctaStart: "ابدأ الآن",
    ctaSignupCrew: "سجّل كحاجز",

    // Crew Hero
    crewBadge: "ابدأ باستقبال الطلبات الآن",
    crewHeroTitle1: "كن",
    crewHeroSpot: "الحاجز",
    crewHeroTitle2: "واكسب من وقتك",
    crewHeroDesc: "استقبل طلبات حجز المواقف من طالبي الموقف القريبين منك، تواصل معهم، واحجز لهم الموقف. اكسب دخل إضافي بكل سهولة!",
    crewAvailable: "طلب متاح للقبول",
    openDashboard: "افتح لوحة التحكم",
    statCrewActive: "حاجز نشط",
    statCompleted: "طلب تم إنجازه",
    statCrewRating: "تقييم الحاجزين",

    // Crew HowItWorks
    crewHowLabel: "كيف تعمل كحاجز؟",
    crewHowTitle: "أربع خطوات بسيطة",
    crewHowDesc: "عملية واضحة وسهلة تخلّيك تبدأ تكسب من وقتك",
    crewStep1Title: "استقبل الطلب",
    crewStep1Desc: "تصلك طلبات حجز المواقف من طالبي الموقف حسب الوجهة المختارة. اختر الطلب المناسب لك واقبله.",
    crewStep2Title: "تواصل مع طالب الموقف",
    crewStep2Desc: "بعد قبول الطلب، تواصل مع طالب الموقف لتنسيق التفاصيل وتأكيد الموقع والوقت المتوقع للوصول.",
    crewStep3Title: "توجّه للموقع",
    crewStep3Desc: "انطلق إلى الوجهة المحددة قبل وصول طالب الموقف وابحث عن موقف مناسب في المنطقة.",
    crewStep4Title: "احجز الموقف",
    crewStep4Desc: "احجز الموقف وانتظر وصول طالب الموقف. بمجرد وصوله واستلامه للموقف، أكمل الطلب واحصل على مكافأتك!",

    // Crew Features
    crewWhyJoin: "ليش تنضم كحاجز؟",
    crewFeatTitle: "مميزات تخلّيك تبدأ اليوم",
    crewFeatIncome: "دخل إضافي",
    crewFeatIncomeDesc: "اكسب مبلغ مقابل كل موقف تحجزه لطالبي الموقف.",
    crewFeatFlex: "مرونة الوقت",
    crewFeatFlexDesc: "اشتغل بالوقت اللي يناسبك بدون التزام.",
    crewFeatNearby: "طلبات قريبة",
    crewFeatNearbyDesc: "استقبل طلبات من مواقع قريبة منك.",
    crewFeatReputation: "بناء سمعة",
    crewFeatReputationDesc: "كل طلب مكتمل يرفع تقييمك ويزيد فرصك.",
    crewFeatNotif: "إشعارات فورية",
    crewFeatNotifDesc: "تنبيهات مباشرة عند وصول طلبات جديدة.",
    crewFeatProtection: "حماية وضمان",
    crewFeatProtectionDesc: "نظام آمن يحفظ حقوقك كحاجز.",

    // Footer
    allRightsReserved: "© 2026 SuperParking. جميع الحقوق محفوظة.",
    privacyPolicy: "سياسة الخصوصية",
    contactUs: "اتصل بنا",

    // Login
    backToHome: "العودة للرئيسية",
    loginTitle: "تسجيل الدخول",
    loginDesc: "أدخل بياناتك للوصول إلى حسابك",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    loggingIn: "جارٍ تسجيل الدخول...",
    loginBtn: "تسجيل الدخول",
    noAccount: "ليس لديك حساب؟",
    signupNow: "سجّل الآن",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    forgotPassword: "نسيت كلمة المرور؟",
    forgotPasswordTitle: "إعادة تعيين كلمة المرور",
    forgotPasswordDesc: "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين",
    sendResetLink: "إرسال رابط إعادة التعيين",
    sendingResetLink: "جارٍ الإرسال...",
    resetLinkSent: "تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني",
    backToLogin: "العودة لتسجيل الدخول",
    resetPasswordTitle: "تعيين كلمة مرور جديدة",
    resetPasswordDesc: "أدخل كلمة المرور الجديدة الخاصة بك",
    resetNewPassword: "كلمة المرور الجديدة",
    resetConfirmPassword: "تأكيد كلمة المرور",
    passwordsNotMatch: "كلمات المرور غير متطابقة",
    passwordTooShort: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
    resetUpdatePassword: "تحديث كلمة المرور",
    updatingPassword: "جارٍ التحديث...",
    resetPasswordSuccess: "تم تحديث كلمة المرور بنجاح",
    invalidResetLink: "رابط إعادة التعيين غير صالح أو منتهي الصلاحية",
    loginSuccess: "تم تسجيل الدخول بنجاح!",

    // Signup
    signupTitle: "إنشاء حساب جديد",
    signupDesc: "انضم إلى SuperParking واحجز موقفك بسهولة",
    fullName: "الاسم الكامل",
    username: "اسم المستخدم",
    passwordMin: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    accountType: "نوع الحساب",
    seekerLabel: "طالب الموقف",
    crewLabel: "أحد أفراد الطاقم",
    creatingAccount: "جارٍ إنشاء الحساب...",
    createAccount: "إنشاء حساب",
    hasAccount: "لديك حساب بالفعل؟",
    loginNow: "سجّل دخولك",
    signupSuccess: "تم إنشاء الحساب! تحقق من بريدك الإلكتروني لتأكيد الحساب.",

    // Dashboard
    welcome: "مرحباً",
    seekerDashLabel: "لوحة تحكم طالب الموقف",
    crewDashLabel: "لوحة تحكم الطاقم",

    // Spot Requester Dashboard
    newBooking: "طلب حجز جديد",
    activeRequests: "طلبات نشطة",
    totalRequests: "إجمالي الطلبات",
    pastRequests: "طلبات سابقة",
    activeTab: "النشطة",
    pastTab: "السابقة",
    location: "الموقع",
    vehiclePlate: "لوحة السيارة",
    crewVehicle: "سيارة الطاقم",
    date: "الموعد",
    status: "الحالة",
    chat: "محادثة",
    completeOrder: "إكتمال الطلب",
    completing: "جاري...",
    confirmComplete: "تأكيد إكتمال الطلب",
    confirmCompleteDesc: "هل أنت متأكد من إكتمال هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.",
    yesComplete: "نعم، إكتمال الطلب",
    cancel: "إلغاء",
    cancelling: "جاري الإلغاء...",
    delete: "حذف",
    deleting: "جاري الحذف...",
    noBookings: "لا توجد طلبات حجز",
    confirmDelete: "هل أنت متأكد من حذف هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.",

    // Statuses
    statusPending: "قيد الانتظار",
    statusApproved: "مقبول",
    statusRejected: "مرفوض",
    statusCompleted: "مكتمل",
    statusCancelled: "ملغي",
    statusCrewApproved: "تم القبول",

    // Crew cancellation (unable to provide a spot)
    crewUnableTitle: "تعذّر توفير موقف",
    crewUnableBtn: "تعذّر توفير موقف",
    crewUnableDesc: "سيتم إلغاء إسنادك للطلب واسترداد المبلغ كاملًا لطالب الموقف. اختر السبب.",
    cancelReasonLabel: "سبب الاعتذار",
    cancelReasonPlaceholder: "اختر السبب",
    cancelReasonNote: "ملاحظة إضافية",
    cancelReasonNoteRequired: "الملاحظة إلزامية عند اختيار «سبب آخر»",
    reason_no_spots: "لا تتوفر مواقف في الموقع",
    reason_vehicle_issue: "عطل في المركبة",
    reason_emergency: "ظرف طارئ",
    reason_cannot_arrive: "تعذّر الوصول في الوقت المطلوب",
    reason_other: "سبب آخر",
    confirmUnable: "تأكيد الاعتذار",
    submittingUnable: "جاري الإلغاء...",
    cancelledByCrew: "اعتذر الطاقم",
    reason_seeker_no_crew: "إلغاء من طالب الموقف - لم يقبل أي فرد من الطاقم",
    cancelRefund: "إلغاء واسترداد",
    cancelRefundTitle: "إلغاء الطلب واسترداد المبلغ",
    cancelRefundDesc: "لم يقبل أي فرد من الطاقم طلبك بعد. سيتم إلغاء الطلب واسترداد المبلغ المدفوع كاملًا.",
    cancelRefundConfirm: "تأكيد الإلغاء والاسترداد",
    cancelRefundDone: "تم إلغاء الطلب وجاري استرداد المبلغ",
    refundRefunded: "تم الاسترداد",
    refundPending: "جاري الاسترداد",
    cancellationsLog: "سجل اعتذارات الطاقم",
    noCancellations: "لا توجد اعتذارات",
    reasonLabel: "السبب",
    bookingsLog: "تفاصيل الطلبات",
    noBookingsAdmin: "لا توجد طلبات",
    amountPaidLabel: "المبلغ المدفوع",
    paymentDateLabel: "تاريخ الدفع",
    refundReasonLabel: "سبب الاسترداد",
    paymentStatusLabel: "حالة الدفع",
    payUnpaid: "غير مدفوع",
    payPaid: "مدفوع",
    payRefunded: "مسترد",
    payRefundPending: "استرداد قيد التنفيذ",
    notPaidYet: "لم يتم الدفع",



    // Crew Dashboard
    walletBalance: "رصيد المحفظة",
    withdraw: "سحب",
    availableRequests: "طلبات متاحة",
    tasksInProgress: "مهام قيد التنفيذ",
    completedTasks: "مهام مكتملة",
    availableTab: "المتاحة",
    myTasks: "مهامي",
    completedTab: "المكتملة",
    walletTab: "المحفظة",
    accept: "قبول",
    acceptOrder: "قبول الطلب - بيانات سيارتك",
    vehicleName: "اسم السيارة",
    vehiclePlateLabel: "لوحة السيارة *",
    accepting: "جاري القبول...",
    confirmAccept: "تأكيد القبول",
    noAvailable: "لا توجد طلبات متاحة حالياً",
    noActive: "لا توجد مهام قيد التنفيذ",
    noCompleted: "لا توجد مهام مكتملة",
    vehicle: "السيارة",

    // Wallet
    withdrawRequest: "طلب سحب رصيد",
    availableBalance: "الرصيد المتاح:",
    amount: "المبلغ (ر.س) *",
    enterAmount: "أدخل المبلغ",
    accountHolder: "اسم صاحب الحساب *",
    accountHolderPlaceholder: "الاسم كما في الحساب البنكي",
    bankName: "اسم البنك",
    iban: "رقم الآيبان (IBAN) *",
    submitting: "جاري الإرسال...",
    confirmWithdraw: "تأكيد طلب السحب",
    transactionLog: "سجل العمليات",
    withdrawalRequests: "طلبات السحب",
    noTransactions: "لا توجد عمليات بعد",
    noWithdrawals: "لا توجد طلبات سحب بعد",
    description: "الوصف",
    amountLabel: "المبلغ",
    dateLabel: "التاريخ",
    withdrawalPending: "قيد المراجعة",
    withdrawalApproved: "تمت الموافقة",
    withdrawalRejected: "مرفوض",
    sar: "ر.س",

    // Admin
    adminDashboard: "لوحة تحكم المسؤول",
    withdrawalRequestsTitle: "طلبات السحب",
    member: "العضو",
    bank: "البنك",
    ibanLabel: "الآيبان",
    accountHolderName: "اسم صاحب الحساب",
    action: "إجراء",
    approve: "قبول",
    reject: "رفض",
    noWithdrawalRequests: "لا توجد طلبات سحب",
    approved: "تمت الموافقة",
    rejected: "تم الرفض",
    usersTab: "المستخدمين",
    usersTitle: "قائمة المستخدمين",
    usersSearchPlaceholder: "ابحث بالبريد أو الاسم أو اسم المستخدم",
    usersFilterTypeAll: "كل الأنواع",
    usersFilterSeeker: "طالب الموقف",
    usersFilterCrew: "أحد أفراد الطاقم",
    noUsers: "لا يوجد مستخدمون مطابقون",
    userEmail: "البريد الإلكتروني",
    userFullName: "الاسم الكامل",
    userUsername: "اسم المستخدم",
    userAccountType: "نوع الحساب",
    userCreatedAt: "تاريخ التسجيل",


    // Notifications
    enableNotifications: "تفعيل إشعارات التطبيق",
    notificationsPromptDesc: "اسمح بالإشعارات لتصلك تحديثات الطلبات والرسائل فورًا.",
    allowNotifications: "السماح",
    notNow: "ليس الآن",
    notificationsEnabled: "تم تفعيل الإشعارات",
    newMessage: "رسالة جديدة",
    notificationsDenied: "تم رفض الإشعارات. يمكنك تفعيلها من إعدادات الجهاز.",
    notificationsAlreadyEnabled: "الإشعارات مفعّلة بالفعل",
    notificationsUnsupported: "الإشعارات غير مدعومة على هذا الجهاز",
    notificationsSection: "الإشعارات",
    notifications: "الإشعارات",
    markAllRead: "تحديد الكل كمقروء",
    noNotifications: "لا توجد إشعارات",
    now: "الآن",
    minutesAgo: "دقيقة",
    hoursAgo: "ساعة",
    daysAgo: "يوم",
    ago: "منذ",

    // New Booking Dialog
    newBookingTitle: "طلب حجز جديد",
    selectLocation: "حدد موقع الحجز على الخريطة",
    vehicleNameLabel: "اسم السيارة",
    vehiclePlateBooking: "لوحة السيارة",
    expectedArrival: "الوقت المتوقع للوصول",
    bookingCost: "تكلفة الحجز",
    fixedPrice: "سعر ثابت لجميع الحجوزات",
    notes: "ملاحظات (اختياري)",
    processing: "جاري المعالجة...",
    submitAndPay: "إرسال والدفع",
    awaitingPayment: "بانتظار الدفع",
    payNow: "إكمال الدفع",
    selectLocationError: "يرجى تحديد موقع الحجز على الخريطة",
    searchLocation: "ابحث عن موقع...",
    myCurrentLocation: "موقعي الحالي",
    locatingPosition: "جاري تحديد الموقع...",
    mapLoadError: "تعذر تحميل الخريطة",
    selectedPosition: "موقع محدد",
    locationPermissionDenied: "تم رفض إذن الموقع. فعّل إذن الموقع للتطبيق من إعدادات الجهاز ثم حاول مرة أخرى.",
    locationUnavailable: "تعذر تحديد موقعك حالياً. تأكد من تفعيل خدمات الموقع ثم حاول مرة أخرى.",
    streetLabel: "الشارع",
    neighborhoodLabel: "الحي",
    cityLabel: "المدينة",

    // Live Tracking
    liveTracking: "تتبع مباشر",
    destination: "الوجهة",
    crewLocation: "موقع الحاجز",
    crewOnTheWay: "الحاجز في الطريق",
    waitingForCrewLocation: "بانتظار موقع الحاجز...",
    trackCrew: "تتبع",
    crewNearbyTitle: "الحاجز اقترب من الوجهة!",
    crewNearbyDesc: "الحاجز أصبح على بعد أقل من 500 متر من الوجهة",
    km: "كم",
    meter: "متر",

    // Rating
    rateCrewTitle: "قيّم الحاجز",
    rateCrewDesc: "كيف كانت تجربتك مع الحاجز؟",
    submitRating: "إرسال التقييم",
    skipRating: "تخطي",
    ratingSubmitted: "تم إرسال التقييم بنجاح",

    // Chat
    chatTitle: "محادثة",
    noMessages: "لا توجد رسائل بعد. ابدأ المحادثة!",
    typeMessage: "اكتب رسالة...",

    // Payment
    paymentCancelled: "تم إلغاء الدفع",
    paymentCancelledDesc: "تم إلغاء عملية الدفع. طلب الحجز لا يزال محفوظاً ويمكنك إعادة المحاولة من لوحة التحكم.",
    goToDashboard: "الذهاب للوحة التحكم",
    paymentSuccess: "تم الدفع بنجاح!",
    verifying: "جاري التحقق...",
    paymentSuccessDesc: "تم تأكيد دفعتك وسيتم معالجة طلب الحجز الخاص بك قريباً",
    paymentErrorDesc: "حدث خطأ أثناء التحقق من الدفع",

    // Settings
    accountSettings: "إعدادات الحساب",
    fullNameSetting: "الاسم الكامل",
    fullNameDesc: "تعديل اسمك المعروض في التطبيق",
    save: "حفظ",
    saving: "جارٍ الحفظ...",
    emailSetting: "البريد الإلكتروني",
    emailDesc: "تغيير بريدك الإلكتروني يتطلب تأكيداً من البريد الجديد",
    passwordSetting: "كلمة المرور",
    passwordDesc: "تغيير كلمة المرور الخاصة بحسابك",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    updatePassword: "تحديث كلمة المرور",
    nameRequired: "الاسم الكامل مطلوب",
    emailRequired: "البريد الإلكتروني مطلوب",
    passwordMinSetting: "كلمة المرور الجديدة يجب أن تكون 6 أحرف على الأقل",
    passwordMismatch: "كلمة المرور الجديدة غير متطابقة",
    nameUpdated: "تم تحديث الاسم بنجاح",
    nameUpdateError: "حدث خطأ أثناء تحديث الاسم",
    emailConfirmSent: "تم إرسال رابط التأكيد إلى بريدك الإلكتروني الجديد",
    passwordUpdated: "تم تحديث كلمة المرور بنجاح",
    language: "اللغة",
    languageDesc: "تغيير لغة واجهة التطبيق",
    arabic: "العربية",
    english: "English",
    deleteAccount: "حذف الحساب",
    deleteAccountDesc: "حذف حسابك نهائياً مع جميع بياناتك. لا يمكن التراجع عن هذا الإجراء.",
    deleteAccountBtn: "حذف حسابي",
    deleteAccountConfirmTitle: "هل أنت متأكد؟",
    deleteAccountConfirmDesc: "سيتم حذف حسابك وجميع بياناتك (الحجوزات، الرسائل، التقييمات، المحفظة) نهائياً. لا يمكن استرجاعها.",
    deletingAccount: "جارٍ حذف الحساب...",
    confirmDeleteAccount: "نعم، احذف حسابي",
    accountDeleted: "تم حذف الحساب بنجاح",
    deleteError: "حدث خطأ أثناء حذف الحساب",

    // Install
    installTitle: "تثبيت SuperParking",
    installDesc: "ثبّت التطبيق على جهازك للوصول السريع وتجربة أفضل",
    installed: "تم التثبيت بنجاح!",
    iosSteps: "خطوات التثبيت على iPhone:",
    iosStep1: "اضغط على زر المشاركة (أسفل الشاشة في Safari)",
    iosStep2: 'اختر "إضافة إلى الشاشة الرئيسية"',
    iosStep3: 'اضغط "إضافة"',
    installBtn: "تثبيت التطبيق",
    openInBrowser: "افتح هذه الصفحة من متصفح الهاتف لتثبيت التطبيق",

    // NotFound
    pageNotFound: "الصفحة غير موجودة",
    returnHome: "العودة للرئيسية",

    // Support
    support: "الدعم والمساندة",
    supportTitle: "الدعم والمساندة",
    supportDesc: "أرسل استفسارك أو طلبك وسنقوم بالرد عليك في أقرب وقت",
    supportSubject: "الموضوع",
    supportSubjectPlaceholder: "اكتب موضوع الاستفسار",
    supportMessage: "الرسالة",
    supportMessagePlaceholder: "اكتب تفاصيل استفسارك أو طلبك...",
    supportSend: "إرسال",
    supportSending: "جاري الإرسال...",
    supportSent: "تم إرسال طلبك بنجاح! سيتم الرد عليك قريباً.",
    supportMyTickets: "طلباتي السابقة",
    supportNoTickets: "لا توجد طلبات سابقة",
    supportOpen: "مفتوح",
    supportClosed: "مغلق",
    supportAdminReply: "رد المسؤول",
    supportTickets: "تذاكر الدعم",
    supportNoTicketsAdmin: "لا توجد تذاكر دعم",
    supportReply: "الرد",
    supportReplyPlaceholder: "اكتب الرد...",
    supportSendReply: "إرسال الرد",
    supportClose: "إغلاق التذكرة",
    supportUser: "المستخدم",

    // Common
    error: "خطأ",
    success: "تم",
    errorOccurred: "حدث خطأ",
  },
  en: {
    // Navbar
    howItWorks: "How it works?",
    features: "Features",
    admin: "Admin",
    dashboard: "Dashboard",
    signOut: "Sign Out",
    login: "Log In",
    signupFree: "Sign Up Free",

    // Hero
    heroBadge: "Reserve your spot before you arrive",
    heroTitle1: "Don't search for a",
    heroSpot: "spot",
    heroTitle2: "Let someone reserve it for you",
    heroDesc: "SuperParking connects you with nearby people who reserve a parking spot for you with their vehicle until you arrive. Save your time and nerves!",
    statSpots: "spots reserved",
    statCrew: "active crew",
    statRating: "user rating",

    // HowItWorks
    howLabel: "How it works?",
    howTitle: "Just three steps",
    howDesc: "A simple and fast process to get your spot hassle-free",
    step1Title: "Set your destination",
    step1Desc: "Enter the location you're heading to and set your expected arrival time.",
    step2Title: "Choose a crew member",
    step2Desc: "Browse nearby crew members and choose the best one based on rating and price.",
    step3Title: "Arrive and find your spot reserved",
    step3Desc: "The crew member holds the spot for you until you arrive. Park with ease!",

    // Features
    whySuperParking: "Why SuperParking?",
    featuresTitle: "Features that give you peace of mind",
    featSaveTime: "Save Time",
    featSaveTimeDesc: "No need to drive around, your spot is ready before you arrive.",
    featSafety: "Safe & Trusted",
    featSafetyDesc: "All crew members are verified and rated by users.",
    featPrice: "Affordable Prices",
    featPriceDesc: "Pay a small amount for your peace of mind.",
    featRating: "Rating System",
    featRatingDesc: "Rate your experience and choose top-rated crew members.",
    featChat: "Direct Chat",
    featChatDesc: "Communicate with your crew member directly through in-app chat.",
    featTracking: "Live Tracking",
    featTrackingDesc: "Track the crew member and spot location on the map in real-time.",
    step1Tip: "Pick your destination and arrival time",
    step2Tip: "Choose the right crew for you",
    step3Tip: "Your spot is ready when you arrive",
    featSaveTimeTip: "Spot ready before you arrive",
    featSafetyTip: "Verified, rated crew members",
    featPriceTip: "Flat fee of 29 SAR",
    featRatingTip: "Rate and see top crew",
    featChatTip: "Instant in-app chat",
    featTrackingTip: "Track the crew on the map",

    // CTA
    ctaTitle: "Ready to reserve your spot?",
    ctaDesc: "Sign up to SuperParking and book your parking spot easily",
    ctaStart: "Get Started",
    ctaSignupCrew: "Sign up as Crew",

    // Crew Hero
    crewBadge: "Start receiving requests now",
    crewHeroTitle1: "Be the",
    crewHeroSpot: "Crew",
    crewHeroTitle2: "and earn from your time",
    crewHeroDesc: "Receive parking reservation requests from nearby spot requesters, communicate with them, and reserve the spot. Earn extra income easily!",
    crewAvailable: "requests available to accept",
    openDashboard: "Open Dashboard",
    statCrewActive: "active crew",
    statCompleted: "requests completed",
    statCrewRating: "crew rating",

    // Crew HowItWorks
    crewHowLabel: "How to work as crew?",
    crewHowTitle: "Four simple steps",
    crewHowDesc: "A clear and easy process to start earning from your time",
    crewStep1Title: "Receive the request",
    crewStep1Desc: "You'll receive parking reservation requests from spot requesters based on the chosen destination. Pick the suitable request and accept it.",
    crewStep2Title: "Contact the spot requester",
    crewStep2Desc: "After accepting the request, communicate with the spot requester to coordinate details and confirm the location and expected arrival time.",
    crewStep3Title: "Head to the location",
    crewStep3Desc: "Go to the specified destination before the spot requester arrives and find a suitable parking spot in the area.",
    crewStep4Title: "Reserve the spot",
    crewStep4Desc: "Reserve the spot and wait for the spot requester to arrive. Once they arrive and take the spot, complete the request and get your reward!",

    // Crew Features
    crewWhyJoin: "Why join as crew?",
    crewFeatTitle: "Benefits to start today",
    crewFeatIncome: "Extra Income",
    crewFeatIncomeDesc: "Earn money for every spot you reserve for spot requesters.",
    crewFeatFlex: "Flexible Time",
    crewFeatFlexDesc: "Work at times that suit you with no commitment.",
    crewFeatNearby: "Nearby Requests",
    crewFeatNearbyDesc: "Receive requests from locations near you.",
    crewFeatReputation: "Build Reputation",
    crewFeatReputationDesc: "Every completed request raises your rating and increases your opportunities.",
    crewFeatNotif: "Instant Notifications",
    crewFeatNotifDesc: "Direct alerts when new requests arrive.",
    crewFeatProtection: "Protection & Guarantee",
    crewFeatProtectionDesc: "A secure system that protects your rights as crew.",

    // Footer
    allRightsReserved: "© 2026 SuperParking. All rights reserved.",
    privacyPolicy: "Privacy Policy",
    contactUs: "Contact Us",

    // Login
    backToHome: "Back to Home",
    loginTitle: "Log In",
    loginDesc: "Enter your credentials to access your account",
    email: "Email",
    password: "Password",
    loggingIn: "Logging in...",
    loginBtn: "Log In",
    noAccount: "Don't have an account?",
    signupNow: "Sign Up Now",
    invalidCredentials: "Invalid email or password",
    forgotPassword: "Forgot password?",
    forgotPasswordTitle: "Reset Password",
    forgotPasswordDesc: "Enter your email and we'll send you a reset link",
    sendResetLink: "Send Reset Link",
    sendingResetLink: "Sending...",
    resetLinkSent: "Reset link sent to your email",
    backToLogin: "Back to Login",
    resetPasswordTitle: "Set New Password",
    resetPasswordDesc: "Enter your new password",
    resetNewPassword: "New Password",
    resetConfirmPassword: "Confirm Password",
    passwordsNotMatch: "Passwords do not match",
    passwordTooShort: "Password must be at least 6 characters",
    resetUpdatePassword: "Update Password",
    updatingPassword: "Updating...",
    resetPasswordSuccess: "Password updated successfully",
    invalidResetLink: "Reset link is invalid or expired",
    loginSuccess: "Logged in successfully!",

    // Signup
    signupTitle: "Create New Account",
    signupDesc: "Join SuperParking and reserve your spot easily",
    fullName: "Full Name",
    username: "Username",
    passwordMin: "Password must be at least 6 characters",
    accountType: "Account Type",
    seekerLabel: "Spot requester",
    crewLabel: "Crew member",
    creatingAccount: "Creating account...",
    createAccount: "Create Account",
    hasAccount: "Already have an account?",
    loginNow: "Log In",
    signupSuccess: "Account created! Check your email to confirm your account.",

    // Dashboard
    welcome: "Welcome",
    seekerDashLabel: "Spot Requester Dashboard",
    crewDashLabel: "Crew Dashboard",

    // Spot Requester Dashboard
    newBooking: "New Booking",
    activeRequests: "Active Requests",
    totalRequests: "Total Requests",
    pastRequests: "Past Requests",
    activeTab: "Active",
    pastTab: "Past",
    location: "Location",
    vehiclePlate: "Vehicle Plate",
    crewVehicle: "Crew Vehicle",
    date: "Date",
    status: "Status",
    chat: "Chat",
    completeOrder: "Complete Order",
    completing: "Completing...",
    confirmComplete: "Confirm Order Completion",
    confirmCompleteDesc: "Are you sure you want to complete this order? This action cannot be undone.",
    yesComplete: "Yes, Complete",
    cancel: "Cancel",
    cancelling: "Cancelling...",
    delete: "Delete",
    deleting: "Deleting...",
    noBookings: "No bookings found",
    confirmDelete: "Are you sure you want to delete this order? This action cannot be undone.",

    // Statuses
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled",
    statusCrewApproved: "Accepted",

    // Crew cancellation (unable to provide a spot)
    crewUnableTitle: "Unable to provide a spot",
    crewUnableBtn: "Can't provide spot",
    crewUnableDesc: "You will be unassigned from this order and the spot requester will be fully refunded. Please select a reason.",
    cancelReasonLabel: "Reason",
    cancelReasonPlaceholder: "Select a reason",
    cancelReasonNote: "Additional note",
    cancelReasonNoteRequired: "A note is required when selecting \"Other\"",
    reason_no_spots: "No parking available at the location",
    reason_vehicle_issue: "Vehicle breakdown",
    reason_emergency: "Emergency",
    reason_cannot_arrive: "Unable to arrive on time",
    reason_other: "Other",
    confirmUnable: "Confirm cancellation",
    submittingUnable: "Cancelling...",
    cancelledByCrew: "Cancelled by crew",
    reason_seeker_no_crew: "Cancelled by requester - no crew accepted",
    cancelRefund: "Cancel & refund",
    cancelRefundTitle: "Cancel booking and refund",
    cancelRefundDesc: "No crew member has accepted your request yet. The booking will be cancelled and the full amount refunded.",
    cancelRefundConfirm: "Confirm cancel & refund",
    cancelRefundDone: "Booking cancelled, refund in progress",
    refundRefunded: "Refunded",
    refundPending: "Refund in progress",
    cancellationsLog: "Crew cancellations log",
    noCancellations: "No cancellations",
    reasonLabel: "Reason",
    bookingsLog: "Booking details",
    noBookingsAdmin: "No bookings",
    amountPaidLabel: "Amount paid",
    paymentDateLabel: "Payment date",
    refundReasonLabel: "Refund reason",
    paymentStatusLabel: "Payment status",
    payUnpaid: "Unpaid",
    payPaid: "Paid",
    payRefunded: "Refunded",
    payRefundPending: "Refund in progress",
    notPaidYet: "Not paid",



    // Crew Dashboard
    walletBalance: "Wallet Balance",
    withdraw: "Withdraw",
    availableRequests: "Available Requests",
    tasksInProgress: "Tasks in Progress",
    completedTasks: "Completed Tasks",
    availableTab: "Available",
    myTasks: "My Tasks",
    completedTab: "Completed",
    walletTab: "Wallet",
    accept: "Accept",
    acceptOrder: "Accept Order - Your Vehicle Details",
    vehicleName: "Vehicle Name",
    vehiclePlateLabel: "Vehicle Plate *",
    accepting: "Accepting...",
    confirmAccept: "Confirm Accept",
    noAvailable: "No available requests at the moment",
    noActive: "No tasks in progress",
    noCompleted: "No completed tasks",
    vehicle: "Vehicle",

    // Wallet
    withdrawRequest: "Withdrawal Request",
    availableBalance: "Available Balance:",
    amount: "Amount (SAR) *",
    enterAmount: "Enter amount",
    accountHolder: "Account Holder Name *",
    accountHolderPlaceholder: "Name as in bank account",
    bankName: "Bank Name",
    iban: "IBAN Number *",
    submitting: "Submitting...",
    confirmWithdraw: "Confirm Withdrawal",
    transactionLog: "Transaction Log",
    withdrawalRequests: "Withdrawal Requests",
    noTransactions: "No transactions yet",
    noWithdrawals: "No withdrawal requests yet",
    description: "Description",
    amountLabel: "Amount",
    dateLabel: "Date",
    withdrawalPending: "Under Review",
    withdrawalApproved: "Approved",
    withdrawalRejected: "Rejected",
    sar: "SAR",

    // Admin
    adminDashboard: "Admin Dashboard",
    withdrawalRequestsTitle: "Withdrawal Requests",
    member: "Member",
    bank: "Bank",
    ibanLabel: "IBAN",
    accountHolderName: "Account Holder",
    action: "Action",
    approve: "Approve",
    reject: "Reject",
    noWithdrawalRequests: "No withdrawal requests",
    approved: "Approved",
    rejected: "Rejected",
    usersTab: "Users",
    usersTitle: "Users List",
    usersSearchPlaceholder: "Search by email, name or username",
    usersFilterTypeAll: "All types",
    usersFilterSeeker: "Spot requester",
    usersFilterCrew: "Crew member",
    noUsers: "No matching users",
    userEmail: "Email",
    userFullName: "Full name",
    userUsername: "Username",
    userAccountType: "Account type",
    userCreatedAt: "Registered at",


    // Notifications
    enableNotifications: "Enable app notifications",
    notificationsPromptDesc: "Allow notifications to get instant booking and message updates.",
    allowNotifications: "Allow",
    notNow: "Not now",
    notificationsEnabled: "Notifications enabled",
    newMessage: "New message",
    notificationsDenied: "Notifications were denied. You can enable them in device settings.",
    notificationsAlreadyEnabled: "Notifications are already enabled",
    notificationsUnsupported: "Notifications are not supported on this device",
    notificationsSection: "Notifications",
    notifications: "Notifications",
    markAllRead: "Mark all as read",
    noNotifications: "No notifications",
    now: "Now",
    minutesAgo: "min",
    hoursAgo: "hr",
    daysAgo: "day",
    ago: "ago",

    // New Booking Dialog
    newBookingTitle: "New Booking Request",
    selectLocation: "Select booking location on map",
    vehicleNameLabel: "Vehicle Name",
    vehiclePlateBooking: "Vehicle Plate",
    expectedArrival: "Expected Arrival Time",
    bookingCost: "Booking Cost",
    fixedPrice: "Fixed price for all bookings",
    notes: "Notes (optional)",
    processing: "Processing...",
    submitAndPay: "Submit & Pay",
    awaitingPayment: "Awaiting payment",
    payNow: "Complete payment",
    selectLocationError: "Please select a booking location on the map",
    searchLocation: "Search for a location...",
    myCurrentLocation: "My Location",
    locatingPosition: "Locating...",
    mapLoadError: "Failed to load map",
    selectedPosition: "Selected location",
    locationPermissionDenied: "Location permission was denied. Enable location access for the app in device settings and try again.",
    locationUnavailable: "Unable to detect your location right now. Make sure location services are enabled and try again.",
    streetLabel: "Street",
    neighborhoodLabel: "Neighborhood",
    cityLabel: "City",

    // Live Tracking
    liveTracking: "Live Tracking",
    destination: "Destination",
    crewLocation: "Crew Location",
    crewOnTheWay: "Crew on the way",
    waitingForCrewLocation: "Waiting for crew location...",
    trackCrew: "Track",
    crewNearbyTitle: "Crew is nearby!",
    crewNearbyDesc: "The crew member is less than 500 meters from the destination",
    km: "km",
    meter: "m",

    // Rating
    rateCrewTitle: "Rate the Crew",
    rateCrewDesc: "How was your experience with the crew member?",
    submitRating: "Submit Rating",
    skipRating: "Skip",
    ratingSubmitted: "Rating submitted successfully",

    // Chat
    chatTitle: "Chat",
    noMessages: "No messages yet. Start the conversation!",
    typeMessage: "Type a message...",

    // Payment
    paymentCancelled: "Payment Cancelled",
    paymentCancelledDesc: "The payment was cancelled. Your booking request is still saved and you can retry from the dashboard.",
    goToDashboard: "Go to Dashboard",
    paymentSuccess: "Payment Successful!",
    verifying: "Verifying...",
    paymentSuccessDesc: "Your payment has been confirmed and your booking will be processed soon",
    paymentErrorDesc: "An error occurred while verifying payment",

    // Settings
    accountSettings: "Account Settings",
    fullNameSetting: "Full Name",
    fullNameDesc: "Edit your display name in the app",
    save: "Save",
    saving: "Saving...",
    emailSetting: "Email",
    emailDesc: "Changing your email requires confirmation from the new email",
    passwordSetting: "Password",
    passwordDesc: "Change your account password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    updatePassword: "Update Password",
    nameRequired: "Full name is required",
    emailRequired: "Email is required",
    passwordMinSetting: "New password must be at least 6 characters",
    passwordMismatch: "Passwords do not match",
    nameUpdated: "Name updated successfully",
    nameUpdateError: "Error updating name",
    emailConfirmSent: "Confirmation link sent to your new email",
    passwordUpdated: "Password updated successfully",
    language: "Language",
    languageDesc: "Change the app interface language",
    arabic: "العربية",
    english: "English",
    deleteAccount: "Delete Account",
    deleteAccountDesc: "Permanently delete your account and all your data. This action cannot be undone.",
    deleteAccountBtn: "Delete My Account",
    deleteAccountConfirmTitle: "Are you sure?",
    deleteAccountConfirmDesc: "Your account and all related data (bookings, messages, ratings, wallet) will be permanently deleted. This cannot be reversed.",
    deletingAccount: "Deleting account...",
    confirmDeleteAccount: "Yes, delete my account",
    accountDeleted: "Account deleted successfully",
    deleteError: "An error occurred while deleting the account",

    // Install
    installTitle: "Install SuperParking",
    installDesc: "Install the app on your device for quick access and a better experience",
    installed: "Installed successfully!",
    iosSteps: "Installation steps on iPhone:",
    iosStep1: "Tap the Share button (bottom of screen in Safari)",
    iosStep2: 'Choose "Add to Home Screen"',
    iosStep3: 'Tap "Add"',
    installBtn: "Install App",
    openInBrowser: "Open this page in your phone's browser to install the app",

    // NotFound
    pageNotFound: "Page not found",
    returnHome: "Return to Home",

    // Support
    support: "Support",
    supportTitle: "Support & Help",
    supportDesc: "Send your inquiry or request and we will respond as soon as possible",
    supportSubject: "Subject",
    supportSubjectPlaceholder: "Enter the subject of your inquiry",
    supportMessage: "Message",
    supportMessagePlaceholder: "Describe your inquiry or request...",
    supportSend: "Send",
    supportSending: "Sending...",
    supportSent: "Your request has been sent successfully! We will respond soon.",
    supportMyTickets: "My Previous Tickets",
    supportNoTickets: "No previous tickets",
    supportOpen: "Open",
    supportClosed: "Closed",
    supportAdminReply: "Admin Reply",
    supportTickets: "Support Tickets",
    supportNoTicketsAdmin: "No support tickets",
    supportReply: "Reply",
    supportReplyPlaceholder: "Write your reply...",
    supportSendReply: "Send Reply",
    supportClose: "Close Ticket",
    supportUser: "User",

    // Common
    error: "Error",
    success: "Done",
    errorOccurred: "An error occurred",
  },
} as const;

type TranslationKey = keyof typeof translations.ar;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ar",
  setLang: () => {},
  t: (key) => key,
  dir: "rtl",
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("parklet-lang");
    return (saved === "en" || saved === "ar") ? saved : "ar";
  });

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("parklet-lang", newLang);
  };

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.ar[key] || key;
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.dir = dir;
    document.documentElement.lang = lang;
  }, [lang, dir]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};
